2020-06-23 10:28:26 [scrapy.utils.log] INFO: Scrapy 2.1.0 started (bot: scrapy_crawl)
2020-06-23 10:28:26 [scrapy.utils.log] INFO: Versions: lxml 4.5.1.0, libxml2 2.9.10, cssselect 1.1.0, parsel 1.6.0, w3lib 1.22.0, Twisted 20.3.0, Python 3.7.7 (default, Mar 13 2020, 10:23:39) - [GCC 9.2.1 20190827 (Red Hat 9.2.1-1)], pyOpenSSL 19.1.0 (OpenSSL 1.1.1g  21 Apr 2020), cryptography 2.9.2, Platform Linux-5.6.13-200.fc31.x86_64-x86_64-with-fedora-31-Thirty_One
2020-06-23 10:28:26 [scrapy.utils.log] DEBUG: Using reactor: twisted.internet.epollreactor.EPollReactor
2020-06-23 10:28:26 [scrapy.crawler] INFO: Overridden settings:
{'BOT_NAME': 'scrapy_crawl',
 'LOG_FILE': 'logs/default/imdb_crawl/444619bab53c11ea84d4c417fe6cdce7.log',
 'NEWSPIDER_MODULE': 'scrapy_crawl.spiders',
 'ROBOTSTXT_OBEY': True,
 'SPIDER_MODULES': ['scrapy_crawl.spiders']}
2020-06-23 10:28:26 [scrapy.extensions.telnet] INFO: Telnet Password: 1ed61862f66b8b8f
2020-06-23 10:28:26 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.logstats.LogStats']
2020-06-23 10:28:26 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.robotstxt.RobotsTxtMiddleware',
 'scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2020-06-23 10:28:26 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2020-06-23 10:28:26 [scrapy.middleware] INFO: Enabled item pipelines:
['scrapy_crawl.pipelines.ScrapyCrawlPipeline']
2020-06-23 10:28:26 [scrapy.core.engine] INFO: Spider opened
2020-06-23 10:28:26 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2020-06-23 10:28:26 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
2020-06-23 10:28:27 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.imdb.com/robots.txt> (referer: None)
2020-06-23 10:28:30 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.imdb.com/title/tt0241527/> (referer: None)
2020-06-23 10:28:31 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.imdb.com/title/tt0241527/>
{'title': "Harry Potter and the Sorcerer's Stone", 'imdb_id': '0241527'}
2020-06-23 10:28:31 [scrapy.core.engine] INFO: Closing spider (finished)
2020-06-23 10:28:31 [asyncio] DEBUG: Using selector: EpollSelector
2020-06-23 10:28:31 [scrapy.core.engine] ERROR: Scraper close failure
Traceback (most recent call last):
  File "/home/encouse/Documents/api-kinoinfo/scrapy_crawl/scrapy_crawl/pipelines.py", line 15, in close_spider
    film = models.Films.objects.get(imdb_id = self.items['imdb_id'])
  File "/home/encouse/Documents/api-kinoinfo/j/lib64/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/encouse/Documents/api-kinoinfo/j/lib64/python3.7/site-packages/django/db/models/query.py", line 417, in get
    self.model._meta.object_name
base.models.Films.DoesNotExist: Films matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/encouse/Documents/api-kinoinfo/j/lib64/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.NumericValueOutOfRange: bigint out of range


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/encouse/Documents/api-kinoinfo/j/lib64/python3.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/encouse/Documents/api-kinoinfo/scrapy_crawl/scrapy_crawl/pipelines.py", line 22, in close_spider
    film = models.Films.objects.create(id = 318231283792183712532)
  File "/home/encouse/Documents/api-kinoinfo/j/lib64/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/encouse/Documents/api-kinoinfo/j/lib64/python3.7/site-packages/django/db/models/query.py", line 433, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/encouse/Documents/api-kinoinfo/j/lib64/python3.7/site-packages/django/db/models/base.py", line 746, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/encouse/Documents/api-kinoinfo/j/lib64/python3.7/site-packages/django/db/models/base.py", line 784, in save_base
    force_update, using, update_fields,
  File "/home/encouse/Documents/api-kinoinfo/j/lib64/python3.7/site-packages/django/db/models/base.py", line 887, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/home/encouse/Documents/api-kinoinfo/j/lib64/python3.7/site-packages/django/db/models/base.py", line 926, in _do_insert
    using=using, raw=raw,
  File "/home/encouse/Documents/api-kinoinfo/j/lib64/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/encouse/Documents/api-kinoinfo/j/lib64/python3.7/site-packages/django/db/models/query.py", line 1204, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/encouse/Documents/api-kinoinfo/j/lib64/python3.7/site-packages/django/db/models/sql/compiler.py", line 1391, in execute_sql
    cursor.execute(sql, params)
  File "/home/encouse/Documents/api-kinoinfo/j/lib64/python3.7/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/encouse/Documents/api-kinoinfo/j/lib64/python3.7/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/encouse/Documents/api-kinoinfo/j/lib64/python3.7/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/encouse/Documents/api-kinoinfo/j/lib64/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/home/encouse/Documents/api-kinoinfo/j/lib64/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/encouse/Documents/api-kinoinfo/j/lib64/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.DataError: bigint out of range

2020-06-23 10:28:31 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 450,
 'downloader/request_count': 2,
 'downloader/request_method_count/GET': 2,
 'downloader/response_bytes': 291849,
 'downloader/response_count': 2,
 'downloader/response_status_count/200': 2,
 'elapsed_time_seconds': 5.002457,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2020, 6, 23, 10, 28, 31, 271146),
 'item_scraped_count': 1,
 'log_count/DEBUG': 4,
 'log_count/ERROR': 1,
 'log_count/INFO': 10,
 'memusage/max': 81793024,
 'memusage/startup': 81793024,
 'response_received_count': 2,
 'robotstxt/request_count': 1,
 'robotstxt/response_count': 1,
 'robotstxt/response_status_count/200': 1,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'start_time': datetime.datetime(2020, 6, 23, 10, 28, 26, 268689)}
2020-06-23 10:28:31 [scrapy.core.engine] INFO: Spider closed (finished)
